SELECT 
		GEOFENCE_CODE,
		GEOFENCE_SID,
		GEOFENCE_NAME, 
		GEOFENCE_TYPE, 
		GEOFENCE_SPEED, 
		GEOFENCE_GEOM 
FROM	
		GEOFENCE 
WHERE	GEOFENCE_GEOM.STPointOnSurface().ToString() IS NOT NULL AND GEOFENCE_GEOM IS NOT NULL