SELECT 
		MAX(B.HISTORY_DATE) AS HISTORY_DATE, MAX(B.HISTORY_LOCATION) AS HISTORY_LOCATION, 
		MAX(B.ORDER_NUMBER) AS ORDER_NUMBER, MAX(B.STATUS) AS STATUS  
FROM DATA_ORDER_HISTORY B WHERE B.ORDER_NUMBER = @ORDER_NUMBER