//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
   
    
    public partial class vwVehicleWithOrder
    {
        public string REG_NO { get; set; }
        public Nullable<bool> LAST_IO1 { get; set; }
        public Nullable<double> LAST_WP_LAT { get; set; }
        public Nullable<double> LAST_WP_LON { get; set; }
        public Nullable<bool> Expr1 { get; set; }
        public Nullable<double> LAST_WP_SPEED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> LAST_ENGINE { get; set; }
        public string POLYGON { get; set; }
        public string VEHICLE_IMEI { get; set; }
        public string WP_PROPINSI { get; set; }
        public string WP_KABUPATEN { get; set; }
        public string WP_KECAMATAN { get; set; }
        public string WP_KELURAHAN { get; set; }
        public Nullable<bool> LAST_IO2 { get; set; }
        public Nullable<bool> LAST_IO3 { get; set; }
        public Nullable<bool> LAST_IO4 { get; set; }
        public Nullable<bool> LAST_IO5 { get; set; }
        public Nullable<bool> LAST_IO6 { get; set; }
        public string CUSTOMER_SID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> PICKUP_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string SUBDIVISION_NAME { get; set; }
        public string DIVISION_NAME { get; set; }
        public string WP_JALAN { get; set; }
        public string NOUNIT { get; set; }
        public string STATUS { get; set; }
        public string DESTINATION_NAME { get; set; }
        public string ORIGIN_NAME { get; set; }
        public Nullable<System.DateTime> EXPIRED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<double> HEADING { get; set; }
        public string VEHICLE_SID { get; set; }
        public string Expr2 { get; set; }
        public Nullable<double> KM_ODO { get; set; }
        public string CELLNO { get; set; }
        public Nullable<double> EXT_POWER { get; set; }
        public Nullable<double> INT_POWER { get; set; }
        public string DRIVER_CELL { get; set; }
        public Nullable<double> SUHU01 { get; set; }
        public Nullable<double> SUHU02 { get; set; }
        public string MODEL_UNIT { get; set; }
        public Nullable<bool> LAST_GPS_STATUS { get; set; }
    }
}
